### PR TITLE
Update mdlp.py

### PR DESCRIPTION
**Pull request by eloaf**
python3 + speedups with better use of numpy

### CODE REVIEW

**Comment by eloaf** [comment]
@maxpumperla

**Comment by maxpumperla** [comment]
@eloaf :D sorry, completely missed this one.

are you interested in a pypi release for this?

**Comment by eloaf** [comment]
I don't mind, I simply made these updates for myself while performing some experiments last year, no longer using it though.

**Comment by eloaf** [comment]
You could probably get even more speedups using numba as well.

**Comment by el-hult** [comment]
fyi I did a numba implementation. it seemed like a too large of a change to upstream, so it is just in my fork. https://github.com/el-hult/entropy-mdlp

**Pull request merged**
